version: '3.7'

services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  php-fpm:
    build: ./dockerfiles/php
    image: php:7.3-fpm-alpine
    volumes:
      - .:/var/www/html
  postgres:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./data:/var/lib/postgresql/data
